### ISSUE TITLE
Possible issue when auto-injecting negative embeddings

### ISSUE THREAD

**Issue by ghost** [Haidra-Org/hordelib#69]
So, I'm not exactly sure if this is a mistake on my part or not, but I've been trying to use negative embeddings in ArtBot and Lucid Creations, and they don't properly work on either of them with auto-injections. ArtBot always injects the embedding, while it's optional with Lucid Creations (so you can inject manually).

Base parameters for all generations:
Base prompt - `1girl, college student, black hair, long hair, glasses, upper body`
Model - `Anything Diffusion`
Resolution - `512x768`
Seed - `1234`
Steps - `30`
Guidance - `7.5`
Sampler - `k_dpmpp_2m`
Karras - `Enabled`
Clip skip - `1` (default)

1) With just those settings with no negative prompt whatsoever:
![image](https://github.com/Haidra-Org/hordelib/assets/21169548/5f7c0215-ac2c-4218-be1f-e72c341e8026) Same generation on ArtBot - https://tinybots.net/artbot?i=h7twhJUM16o

2) Manually injecting [EasyNegative](https://civitai.com/models/7808) (Inject Embedding: `No`) with `(embedding:7808:1)` 
![image](https://github.com/Haidra-Org/hordelib/assets/21169548/41fb2ce2-d6e4-4cdc-9a5b-f83999c82d6a) You can clearly see that the image has become "better" as to normal anime art standards. Not possible to repeat in ArtBot as it always injects embeddings automatically.

3) Automatically injecting the same [EasyNegative](https://civitai.com/models/7808) (Inject Embedding: `Negative prompt`) without specifying anything in the negative prompt. ![image](https://github.com/Haidra-Org/hordelib/assets/21169548/a4381c26-0a9e-4a3c-a0eb-032879908d48) It seems like that in the case of an automatic injection to the negative prompt, the embedding still somehow ends up in the positive prompt, making the image worse. Same generation on ArtBot - https://tinybots.net/artbot?i=gFD6RSgyfWB

**Comment by tazlin** [comment]
Per discussion in discord:

Previous behavior:
```python
{'prompt.text': '(embedding:7523:0.5),Closeup portrait of a Lesotho teenage girl wearing a Seanamarena blanket, walking in a field of flowers, holding a bundle of flowers, detailed background, light rays, atmospheric lighting###,(embedding:7808:0.5),(embedding:64870:0.5)', 'negative_prompt.text': '',}
```

#70 now correctly places embedding syntax in negative_prompt.

**Comment by ghost** [comment]
Thanks! Yeah, this should be fixed once the workers update, closing.

**Comment by tazlin** [comment]
Re-opening as the issue isn't resolved until pushed to the releases branch. I'll tag the issue in the relevant PR and it will close when the fix is live.
